apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge
  namespace: iot-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bridge
  template:
    metadata:
      labels:
        app: bridge
    spec:
      containers:
        - name: bridge
          image: diplomat/bridge:k8s
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: iot-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"