apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-config
  namespace: iot-system
data:
  MQTT_BROKER_URL: "tcp://my-emqx.iot-system.svc.cluster.local:1883"
  KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.iot-system.svc.cluster.local:9092"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.iot-system.svc.cluster.local:9092"
  SPRING_PROFILES_ACTIVE: "k8s"
  DB_HOST: "my-db-postgresql-primary.iot-system.svc.cluster.local"
  DB_NAME: "iot_data"