apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: iot-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: diplomat/consumer:k8s
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: iot-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"