global:
  storageClass: "standard"

architecture: standalone

auth:
  username: "iot_user"
  password: "iot_password"
  database: "iot_data"
  postgresPassword: "admin_password"

primary:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  persistence:
    enabled: false