apiVersion: v1
kind: Secret
metadata:
  name: iot-secrets
  namespace: iot-system
type: Opaque
stringData:
  MQTT_USER: "admin"
  MQTT_PASSWORD: "public"
  DB_USER: "aW90X3VzZXI="
  DB_PASS: "aW90X3Bhc3N3b3Jk"