apiVersion: v1
kind: Secret
metadata:
  name: iot-secrets
  namespace: iot-system
type: Opaque
stringData:
  MQTT_USER: "admin"
  MQTT_PASSWORD: "public"
  DB_USER: "iot_user"
  DB_PASS: "iot_password"