server:
  port: 8080

app:
  mqtt:
    broker-url: ${MQTT_BROKER_URL:tcp://localhost:1883}
    # topics: список MQTT-топиков для подписки
    topics: sensors/#, alerts/#

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      batch-size: 16384
      properties:
        linger.ms: 20
        buffer.memory: 33554432

resilience4j:
  circuitbreaker:
    instances:
      kafkaBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name:bridge-service}